CREATE TYPE "ContentLifecycleStatus" AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
ALTER TABLE "programs" ADD COLUMN "status" "ContentLifecycleStatus" NOT NULL DEFAULT 'DRAFT';
ALTER TABLE "teacher_profiles" ADD COLUMN "status" "ContentLifecycleStatus" NOT NULL DEFAULT 'DRAFT';
ALTER TABLE "gallery_albums" ADD COLUMN "status" "ContentLifecycleStatus" NOT NULL DEFAULT 'DRAFT';
ALTER TABLE "testimonials" ADD COLUMN "status" "ContentLifecycleStatus" NOT NULL DEFAULT 'DRAFT';
UPDATE "programs" SET "status"=CASE WHEN "isActive" THEN 'DRAFT'::"ContentLifecycleStatus" ELSE 'ARCHIVED'::"ContentLifecycleStatus" END;
UPDATE "teacher_profiles" SET "status"=CASE WHEN "isActive" THEN 'DRAFT'::"ContentLifecycleStatus" ELSE 'ARCHIVED'::"ContentLifecycleStatus" END;
UPDATE "gallery_albums" SET "status"=CASE WHEN "isActive" THEN 'DRAFT'::"ContentLifecycleStatus" ELSE 'ARCHIVED'::"ContentLifecycleStatus" END;
UPDATE "testimonials" SET "status"=CASE WHEN "isActive" THEN 'DRAFT'::"ContentLifecycleStatus" ELSE 'ARCHIVED'::"ContentLifecycleStatus" END;
CREATE TABLE "content_publications" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"entityType" VARCHAR(40) NOT NULL,"entityId" UUID NOT NULL,"slug" VARCHAR(120),"payload" JSONB NOT NULL,"version" INTEGER NOT NULL,"sourceUpdatedAt" TIMESTAMPTZ(3) NOT NULL,"publishedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"publishedByUserId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "content_publications_pkey" PRIMARY KEY("id"));
CREATE TABLE "content_publication_heads" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"entityType" VARCHAR(40) NOT NULL,"entityId" UUID NOT NULL,"currentPublicationId" UUID NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "content_publication_heads_pkey" PRIMARY KEY("id"));
CREATE TABLE "content_audit_events" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"actorUserId" UUID NOT NULL,"entityType" VARCHAR(40) NOT NULL,"entityId" UUID NOT NULL,"action" VARCHAR(40) NOT NULL,"fromStatus" "ContentLifecycleStatus","toStatus" "ContentLifecycleStatus" NOT NULL,"sourceUpdatedAt" TIMESTAMPTZ(3) NOT NULL,"requestId" VARCHAR(100) NOT NULL,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "content_audit_events_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "content_publications_id_schoolId_entityType_entityId_key" ON "content_publications"("id","schoolId","entityType","entityId");
CREATE UNIQUE INDEX "content_publications_schoolId_entityType_entityId_version_key" ON "content_publications"("schoolId","entityType","entityId","version");
CREATE INDEX "content_publications_schoolId_entityType_publishedAt_idx" ON "content_publications"("schoolId","entityType","publishedAt");
CREATE UNIQUE INDEX "content_publication_heads_currentPublicationId_key" ON "content_publication_heads"("currentPublicationId");
CREATE UNIQUE INDEX "content_publication_heads_schoolId_entityType_entityId_key" ON "content_publication_heads"("schoolId","entityType","entityId");
CREATE UNIQUE INDEX "content_publication_heads_currentPublicationId_schoolId_entityType_entityId_key" ON "content_publication_heads"("currentPublicationId","schoolId","entityType","entityId");
CREATE INDEX "content_publication_heads_schoolId_entityType_updatedAt_idx" ON "content_publication_heads"("schoolId","entityType","updatedAt");
CREATE INDEX "content_audit_events_schoolId_entityType_entityId_createdAt_idx" ON "content_audit_events"("schoolId","entityType","entityId","createdAt");
CREATE INDEX "content_audit_events_requestId_idx" ON "content_audit_events"("requestId");
ALTER TABLE "content_publications" ADD CONSTRAINT "content_publications_schoolId_fkey" FOREIGN KEY("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "content_publication_heads" ADD CONSTRAINT "content_publication_heads_schoolId_fkey" FOREIGN KEY("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "content_publication_heads" ADD CONSTRAINT "content_publication_heads_currentPublicationId_schoolId_entityType_entityId_fkey" FOREIGN KEY("currentPublicationId","schoolId","entityType","entityId") REFERENCES "content_publications"("id","schoolId","entityType","entityId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "content_audit_events" ADD CONSTRAINT "content_audit_events_schoolId_fkey" FOREIGN KEY("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
