CREATE TABLE "programs" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"code" VARCHAR(64) NOT NULL,"title" VARCHAR(120) NOT NULL,"slug" VARCHAR(120) NOT NULL,"summary" VARCHAR(300) NOT NULL,"description" VARCHAR(10000) NOT NULL,"featuredMediaId" UUID,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "programs_pkey" PRIMARY KEY ("id"));
CREATE TABLE "teacher_profiles" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"name" VARCHAR(120) NOT NULL,"position" VARCHAR(120),"biography" VARCHAR(2000),"qualification" VARCHAR(200),"photoMediaId" UUID,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "teacher_profiles_pkey" PRIMARY KEY ("id"));
CREATE TABLE "gallery_albums" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"title" VARCHAR(150) NOT NULL,"slug" VARCHAR(120) NOT NULL,"description" VARCHAR(2000),"coverMediaId" UUID,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "gallery_albums_pkey" PRIMARY KEY ("id"));
CREATE TABLE "gallery_items" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"albumId" UUID NOT NULL,"mediaId" UUID NOT NULL,"caption" VARCHAR(500),"sortOrder" INTEGER NOT NULL DEFAULT 0,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "gallery_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "testimonials" ("id" UUID NOT NULL,"schoolId" UUID NOT NULL,"authorName" VARCHAR(120) NOT NULL,"authorRole" VARCHAR(120),"quote" VARCHAR(2000) NOT NULL,"avatarMediaId" UUID,"sortOrder" INTEGER NOT NULL DEFAULT 0,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "testimonials_pkey" PRIMARY KEY ("id"));
CREATE INDEX "programs_schoolId_isActive_sortOrder_idx" ON "programs"("schoolId","isActive","sortOrder");
CREATE UNIQUE INDEX "programs_schoolId_code_key" ON "programs"("schoolId","code");
CREATE UNIQUE INDEX "programs_schoolId_slug_key" ON "programs"("schoolId","slug");
CREATE INDEX "teacher_profiles_schoolId_isActive_sortOrder_idx" ON "teacher_profiles"("schoolId","isActive","sortOrder");
CREATE INDEX "gallery_albums_schoolId_isActive_sortOrder_idx" ON "gallery_albums"("schoolId","isActive","sortOrder");
CREATE UNIQUE INDEX "gallery_albums_schoolId_slug_key" ON "gallery_albums"("schoolId","slug");
CREATE INDEX "gallery_items_schoolId_albumId_isActive_sortOrder_idx" ON "gallery_items"("schoolId","albumId","isActive","sortOrder");
CREATE UNIQUE INDEX "gallery_items_albumId_mediaId_key" ON "gallery_items"("albumId","mediaId");
CREATE INDEX "testimonials_schoolId_isActive_sortOrder_idx" ON "testimonials"("schoolId","isActive","sortOrder");
ALTER TABLE "programs" ADD CONSTRAINT "programs_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "programs" ADD CONSTRAINT "programs_featuredMediaId_fkey" FOREIGN KEY ("featuredMediaId") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "teacher_profiles" ADD CONSTRAINT "teacher_profiles_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "teacher_profiles" ADD CONSTRAINT "teacher_profiles_photoMediaId_fkey" FOREIGN KEY ("photoMediaId") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "gallery_albums" ADD CONSTRAINT "gallery_albums_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "gallery_albums" ADD CONSTRAINT "gallery_albums_coverMediaId_fkey" FOREIGN KEY ("coverMediaId") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "gallery_items" ADD CONSTRAINT "gallery_items_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "gallery_items" ADD CONSTRAINT "gallery_items_albumId_fkey" FOREIGN KEY ("albumId") REFERENCES "gallery_albums"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "gallery_items" ADD CONSTRAINT "gallery_items_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "testimonials" ADD CONSTRAINT "testimonials_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "testimonials" ADD CONSTRAINT "testimonials_avatarMediaId_fkey" FOREIGN KEY ("avatarMediaId") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
