import{Prisma}from"@/generated/prisma/client";
import{prisma}from"@/lib/prisma";
import{ApplicationError,entityNotFound,staleUpdate}from"@/modules/cms/domain/errors";
import type{PublicationSnapshot,PublishableType,PublishingRepository}from"../domain/contracts";

const usable=(status:string)=>status==="ACTIVE"||status==="READY";
const mediaPublic=(m:{id:string;mimeType:string;width:number|null;height:number|null;altText:string|null;caption:string|null})=>({id:m.id,mimeType:m.mimeType,width:m.width,height:m.height,altText:m.altText,caption:m.caption});
const invalid=(message:string)=>new ApplicationError("PUBLISH_VALIDATION_FAILED",422,message);

export class PrismaPublishingRepository implements PublishingRepository{
 async publish(input:{schoolId:string;entityType:PublishableType;entityId:string;expectedUpdatedAt:Date;actorUserId:string;requestId:string}){return prisma.$transaction(async tx=>{
  const working=await this.snapshot(tx,input.schoolId,input.entityType,input.entityId);
  if(!working)throw entityNotFound();if(working.status==="ARCHIVED")throw new ApplicationError("PUBLICATION_CONFLICT",409,"Archived content must be restored before publishing.");if(working.updatedAt.getTime()!==input.expectedUpdatedAt.getTime())throw staleUpdate();
  const updated=await this.setStatus(tx,input.schoolId,input.entityType,input.entityId,input.expectedUpdatedAt,"PUBLISHED");
  const aggregate=await tx.contentPublication.aggregate({where:{schoolId:input.schoolId,entityType:input.entityType,entityId:input.entityId},_max:{version:true}});const version=(aggregate._max.version??0)+1;
  const publication=await tx.contentPublication.create({data:{schoolId:input.schoolId,entityType:input.entityType,entityId:input.entityId,slug:working.slug,payload:working.payload as Prisma.InputJsonValue,version,sourceUpdatedAt:updated.updatedAt,publishedByUserId:input.actorUserId}});
  await tx.contentPublicationHead.upsert({where:{schoolId_entityType_entityId:{schoolId:input.schoolId,entityType:input.entityType,entityId:input.entityId}},create:{schoolId:input.schoolId,entityType:input.entityType,entityId:input.entityId,currentPublicationId:publication.id},update:{currentPublicationId:publication.id}});
  await tx.contentAuditEvent.create({data:{schoolId:input.schoolId,actorUserId:input.actorUserId,entityType:input.entityType,entityId:input.entityId,action:working.status==="PUBLISHED"?"REPUBLISH":"PUBLISH",fromStatus:working.status,toStatus:"PUBLISHED",sourceUpdatedAt:updated.updatedAt,requestId:input.requestId}});
  return this.map(publication,input.entityType);
 });}
 async unpublish(input:{schoolId:string;entityType:PublishableType;entityId:string;expectedUpdatedAt:Date;actorUserId:string;requestId:string}){await prisma.$transaction(async tx=>{const working=await this.workingState(tx,input.schoolId,input.entityType,input.entityId);if(!working)throw entityNotFound();if(working.updatedAt.getTime()!==input.expectedUpdatedAt.getTime())throw staleUpdate();const removed=await tx.contentPublicationHead.deleteMany({where:{schoolId:input.schoolId,entityType:input.entityType,entityId:input.entityId}});if(!removed.count)throw new ApplicationError("PUBLICATION_CONFLICT",409,"Content is not currently published.");const updated=await this.setStatus(tx,input.schoolId,input.entityType,input.entityId,input.expectedUpdatedAt,"DRAFT");await tx.contentAuditEvent.create({data:{schoolId:input.schoolId,actorUserId:input.actorUserId,entityType:input.entityType,entityId:input.entityId,action:"UNPUBLISH",fromStatus:working.status,toStatus:"DRAFT",sourceUpdatedAt:updated.updatedAt,requestId:input.requestId}});});}
 async status(s:string,t:PublishableType,id:string){const working=await this.workingState(prisma,s,t,id);if(!working)throw entityNotFound();const head=await prisma.contentPublicationHead.findUnique({where:{schoolId_entityType_entityId:{schoolId:s,entityType:t,entityId:id}},include:{currentPublication:true}});return{status:working.status,current:head?this.map(head.currentPublication,t):null,hasUnpublishedChanges:!!head&&working.updatedAt.getTime()!==head.currentPublication.sourceUpdatedAt.getTime()};}
 async listPublished(s:string,t:PublishableType){const heads=await prisma.contentPublicationHead.findMany({where:{schoolId:s,entityType:t},include:{currentPublication:true}});return heads.map(h=>this.map(h.currentPublication,t)).sort((a,b)=>Number((a.payload as{sortOrder?:number}).sortOrder??0)-Number((b.payload as{sortOrder?:number}).sortOrder??0)||a.entityId.localeCompare(b.entityId));}
 async readPublished(s:string,t:PublishableType,id:string){const h=await prisma.contentPublicationHead.findUnique({where:{schoolId_entityType_entityId:{schoolId:s,entityType:t,entityId:id}},include:{currentPublication:true}});return h?this.map(h.currentPublication,t):null;}
 private map(p:{id:string;schoolId:string;entityId:string;version:number;payload:unknown;publishedAt:Date;sourceUpdatedAt:Date},t:PublishableType):PublicationSnapshot{return{id:p.id,schoolId:p.schoolId,entityType:t,entityId:p.entityId,version:p.version,payload:p.payload,publishedAt:p.publishedAt,sourceUpdatedAt:p.sourceUpdatedAt};}
 private workingState(tx:Prisma.TransactionClient|typeof prisma,s:string,t:PublishableType,id:string){switch(t){case"PROGRAM":return tx.program.findFirst({where:{schoolId:s,id},select:{status:true,updatedAt:true}});case"TEACHER_PROFILE":return tx.teacherProfile.findFirst({where:{schoolId:s,id},select:{status:true,updatedAt:true}});case"GALLERY_ALBUM":return tx.galleryAlbum.findFirst({where:{schoolId:s,id},select:{status:true,updatedAt:true}});case"TESTIMONIAL":return tx.testimonial.findFirst({where:{schoolId:s,id},select:{status:true,updatedAt:true}});case"SCHOOL_IDENTITY":return tx.schoolIdentity.findFirst({where:{schoolId:s,id},select:{status:true,updatedAt:true}});case"SCHOOL_PROFILE":return tx.schoolProfile.findFirst({where:{schoolId:s,id},select:{status:true,updatedAt:true}});}}
 private async setStatus(tx:Prisma.TransactionClient,s:string,t:PublishableType,id:string,u:Date,status:"DRAFT"|"PUBLISHED"){let count=0;switch(t){case"PROGRAM":count=(await tx.program.updateMany({where:{schoolId:s,id,updatedAt:u},data:{status}})).count;break;case"TEACHER_PROFILE":count=(await tx.teacherProfile.updateMany({where:{schoolId:s,id,updatedAt:u},data:{status}})).count;break;case"GALLERY_ALBUM":count=(await tx.galleryAlbum.updateMany({where:{schoolId:s,id,updatedAt:u},data:{status}})).count;break;case"TESTIMONIAL":count=(await tx.testimonial.updateMany({where:{schoolId:s,id,updatedAt:u},data:{status}})).count;break;case"SCHOOL_IDENTITY":count=(await tx.schoolIdentity.updateMany({where:{schoolId:s,id,updatedAt:u},data:{status}})).count;break;case"SCHOOL_PROFILE":count=(await tx.schoolProfile.updateMany({where:{schoolId:s,id,updatedAt:u},data:{status}})).count;}if(!count)throw staleUpdate();return(await this.workingState(tx,s,t,id))!;}
 private async snapshot(tx:Prisma.TransactionClient,s:string,t:PublishableType,id:string):Promise<{status:"DRAFT"|"PUBLISHED"|"ARCHIVED";updatedAt:Date;slug:string|null;payload:unknown}|null>{
  if(t==="SCHOOL_IDENTITY"){const x=await tx.schoolIdentity.findFirst({where:{schoolId:s,id},include:{logoMedia:true,logoDarkMedia:true,faviconMedia:true}});if(!x)return null;if(!x.schoolName.trim())throw invalid("School name is required.");if([x.logoMedia,x.logoDarkMedia,x.faviconMedia].some(m=>m&&!usable(m.status)))throw invalid("Identity media is not usable.");return{status:x.status,updatedAt:x.updatedAt,slug:null,payload:{id:x.id,schoolName:x.schoolName,shortName:x.shortName,tagline:x.tagline,logoMedia:x.logoMedia?mediaPublic(x.logoMedia):null,logoDarkMedia:x.logoDarkMedia?mediaPublic(x.logoDarkMedia):null,faviconMedia:x.faviconMedia?mediaPublic(x.faviconMedia):null}};}
  if(t==="SCHOOL_PROFILE"){const x=await tx.schoolProfile.findFirst({where:{schoolId:s,id},include:{principalPhoto:true}});if(!x)return null;if(!x.vision?.trim()||!x.mission?.trim())throw invalid("Vision and mission are required before publishing.");if(x.principalPhoto&&!usable(x.principalPhoto.status))throw invalid("Principal photo is not usable.");return{status:x.status,updatedAt:x.updatedAt,slug:null,payload:{id:x.id,summary:x.summary,history:x.history,vision:x.vision,mission:x.mission,principalName:x.principalName,principalGreeting:x.principalGreeting,values:x.valuesJson,principalPhoto:x.principalPhoto?mediaPublic(x.principalPhoto):null}};}
  if(t==="PROGRAM"){const x=await tx.program.findFirst({where:{schoolId:s,id},include:{featuredMedia:true}});if(!x)return null;if(!x.isActive)throw invalid("Inactive content cannot be published.");if(!x.code.trim()||!x.title.trim()||!x.slug.trim()||!x.summary.trim()||!x.description.trim())throw invalid("Program content is incomplete.");if(x.featuredMedia&&!usable(x.featuredMedia.status))throw invalid("Featured media is not usable.");return{status:x.status,updatedAt:x.updatedAt,slug:x.slug,payload:{id:x.id,code:x.code,title:x.title,slug:x.slug,summary:x.summary,description:x.description,featuredMedia:x.featuredMedia?mediaPublic(x.featuredMedia):null,sortOrder:x.sortOrder}};}
  if(t==="TEACHER_PROFILE"){const x=await tx.teacherProfile.findFirst({where:{schoolId:s,id},include:{photoMedia:true}});if(!x)return null;if(!x.isActive||!x.name.trim())throw invalid("Teacher profile is inactive or incomplete.");if(x.photoMedia&&!usable(x.photoMedia.status))throw invalid("Teacher photo is not usable.");return{status:x.status,updatedAt:x.updatedAt,slug:null,payload:{id:x.id,name:x.name,position:x.position,biography:x.biography,qualification:x.qualification,photoMedia:x.photoMedia?mediaPublic(x.photoMedia):null,sortOrder:x.sortOrder}};}
  if(t==="TESTIMONIAL"){const x=await tx.testimonial.findFirst({where:{schoolId:s,id},include:{avatarMedia:true}});if(!x)return null;if(!x.isActive||!x.authorName.trim()||!x.quote.trim())throw invalid("Testimonial is inactive or incomplete.");if(x.avatarMedia&&!usable(x.avatarMedia.status))throw invalid("Testimonial avatar is not usable.");return{status:x.status,updatedAt:x.updatedAt,slug:null,payload:{id:x.id,authorName:x.authorName,authorRole:x.authorRole,quote:x.quote,avatarMedia:x.avatarMedia?mediaPublic(x.avatarMedia):null,sortOrder:x.sortOrder}};}
  const x=await tx.galleryAlbum.findFirst({where:{schoolId:s,id},include:{coverMedia:true,items:{where:{isActive:true},orderBy:[{sortOrder:"asc"},{id:"asc"}],include:{media:true}}}});if(!x)return null;if(!x.isActive||!x.title.trim()||!x.slug.trim())throw invalid("Gallery album is inactive or incomplete.");if(x.coverMedia&&!usable(x.coverMedia.status))throw invalid("Gallery cover is not usable.");if(x.items.some(i=>!usable(i.media.status)))throw invalid("A gallery item has unusable media.");return{status:x.status,updatedAt:x.updatedAt,slug:x.slug,payload:{id:x.id,title:x.title,slug:x.slug,description:x.description,coverMedia:x.coverMedia?mediaPublic(x.coverMedia):null,sortOrder:x.sortOrder,items:x.items.map(i=>({id:i.id,caption:i.caption,sortOrder:i.sortOrder,media:mediaPublic(i.media)}))}};
 }
}
