import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{prisma}from"@/lib/prisma";
import{PrismaPublishingRepository}from"@/modules/publishing/infrastructure/prisma-publishing-repository";
let school:string,other:string,actor:string,media:string,program:string,album:string;
async function clean(){await prisma.contentPublicationHead.deleteMany();await prisma.contentPublication.deleteMany();await prisma.contentAuditEvent.deleteMany();await prisma.schoolIdentity.deleteMany();await prisma.schoolProfile.deleteMany();await prisma.galleryItem.deleteMany();await prisma.program.deleteMany();await prisma.teacherProfile.deleteMany();await prisma.galleryAlbum.deleteMany();await prisma.testimonial.deleteMany();await prisma.mediaAsset.deleteMany();await prisma.contactChannel.deleteMany();await prisma.socialLink.deleteMany();await prisma.callToAction.deleteMany();await prisma.auditLog.deleteMany();await prisma.schoolSettings.deleteMany();await prisma.school.deleteMany();}
describe.sequential("immutable publishing PostgreSQL integration",()=>{
 beforeAll(async()=>{if(new URL(process.env.DATABASE_URL??"").pathname!=="/arrahmah_sms_test")throw new Error("Test DB required");await clean();actor=crypto.randomUUID();[school,other]=(await Promise.all([prisma.school.create({data:{schoolCode:"PUB_A",schoolName:"A"}}),prisma.school.create({data:{schoolCode:"PUB_B",schoolName:"B"}})])).map(x=>x.id);media=(await prisma.mediaAsset.create({data:{schoolId:school,storageProvider:"TEST",storageKey:"pub/a.jpg",originalFilename:"a.jpg",mimeType:"image/jpeg",sizeBytes:3,checksum:"d".repeat(64),status:"ACTIVE",createdBy:actor,altText:"Anak belajar"}})).id;program=(await prisma.program.create({data:{schoolId:school,code:"ONE",title:"One",slug:"one",summary:"Summary",description:"Description",featuredMediaId:media}})).id;album=(await prisma.galleryAlbum.create({data:{schoolId:school,title:"Album",slug:"album",coverMediaId:media,items:{create:[{schoolId:school,mediaId:media,caption:"Active",sortOrder:0,isActive:true}]}}})).id;});afterAll(async()=>{await clean();await prisma.$disconnect();});
 it("publishes, republishes immutably, and exposes only the head",async()=>{const r=new PrismaPublishingRepository();let w=await prisma.program.findUniqueOrThrow({where:{id:program}});const first=await r.publish({schoolId:school,entityType:"PROGRAM",entityId:program,expectedUpdatedAt:w.updatedAt,actorUserId:actor,requestId:"p1"});expect(first.version).toBe(1);expect((await r.listPublished(school,"PROGRAM"))).toHaveLength(1);await prisma.program.update({where:{id:program},data:{title:"Two"}});w=await prisma.program.findUniqueOrThrow({where:{id:program}});const second=await r.publish({schoolId:school,entityType:"PROGRAM",entityId:program,expectedUpdatedAt:w.updatedAt,actorUserId:actor,requestId:"p2"});expect(second.version).toBe(2);expect(await prisma.contentPublication.count({where:{entityId:program}})).toBe(2);expect(((await r.readPublished(school,"PROGRAM",program))!.payload as{title:string}).title).toBe("Two");expect(await r.readPublished(other,"PROGRAM",program)).toBeNull();});
 it("unpublishes without mutating history and returns working copy to DRAFT",async()=>{const r=new PrismaPublishingRepository();const w=await prisma.program.findUniqueOrThrow({where:{id:program}});await r.unpublish({schoolId:school,entityType:"PROGRAM",entityId:program,expectedUpdatedAt:w.updatedAt,actorUserId:actor,requestId:"u1"});expect(await r.readPublished(school,"PROGRAM",program)).toBeNull();expect(await prisma.contentPublication.count({where:{entityId:program}})).toBe(2);expect((await prisma.program.findUniqueOrThrow({where:{id:program}})).status).toBe("DRAFT");expect(await prisma.contentAuditEvent.count({where:{entityId:program}})).toBe(3);});
 it("embeds ordered active Gallery Items and rejects stale writes",async()=>{const r=new PrismaPublishingRepository();const w=await prisma.galleryAlbum.findUniqueOrThrow({where:{id:album}});const p=await r.publish({schoolId:school,entityType:"GALLERY_ALBUM",entityId:album,expectedUpdatedAt:w.updatedAt,actorUserId:actor,requestId:"g1"});expect((p.payload as{items:unknown[]}).items).toHaveLength(1);await expect(r.publish({schoolId:school,entityType:"GALLERY_ALBUM",entityId:album,expectedUpdatedAt:w.updatedAt,actorUserId:actor,requestId:"stale"})).rejects.toMatchObject({code:"STALE_UPDATE"});expect(await prisma.contentPublication.count({where:{entityId:album}})).toBe(1);});
 it("rejects inactive working copies without creating history, a head, or an audit",async()=>{const r=new PrismaPublishingRepository();const inactive=await prisma.program.create({data:{schoolId:school,code:"OFF",title:"Inactive",slug:"inactive",summary:"Summary",description:"Description",isActive:false}});await expect(r.publish({schoolId:school,entityType:"PROGRAM",entityId:inactive.id,expectedUpdatedAt:inactive.updatedAt,actorUserId:actor,requestId:"inactive"})).rejects.toMatchObject({code:"PUBLISH_VALIDATION_FAILED"});expect(await prisma.contentPublication.count({where:{entityId:inactive.id}})).toBe(0);expect(await prisma.contentPublicationHead.count({where:{entityId:inactive.id}})).toBe(0);expect(await prisma.contentAuditEvent.count({where:{entityId:inactive.id}})).toBe(0);});
 it("rolls back publishing when referenced media is not usable",async()=>{const r=new PrismaPublishingRepository();const unusable=await prisma.mediaAsset.create({data:{schoolId:school,storageProvider:"TEST",storageKey:"pub/archived.jpg",originalFilename:"archived.jpg",mimeType:"image/jpeg",sizeBytes:3,checksum:"e".repeat(64),status:"ARCHIVED",createdBy:actor}});const teacher=await prisma.teacherProfile.create({data:{schoolId:school,name:"Teacher",photoMediaId:unusable.id}});await expect(r.publish({schoolId:school,entityType:"TEACHER_PROFILE",entityId:teacher.id,expectedUpdatedAt:teacher.updatedAt,actorUserId:actor,requestId:"bad-media"})).rejects.toMatchObject({code:"PUBLISH_VALIDATION_FAILED"});expect((await prisma.teacherProfile.findUniqueOrThrow({where:{id:teacher.id}})).status).toBe("DRAFT");expect(await prisma.contentPublication.count({where:{entityId:teacher.id}})).toBe(0);expect(await prisma.contentPublicationHead.count({where:{entityId:teacher.id}})).toBe(0);});
});
