import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { prisma } from "@/lib/prisma";
import { PrismaPublishingRepository } from "@/modules/publishing/infrastructure/prisma-publishing-repository";
import { PrismaSchoolContentRepository } from "@/modules/school-content/infrastructure/prisma-repository";
let schoolId:string,otherSchoolId:string,actorId:string;
async function clean(){await prisma.contentPublicationHead.deleteMany();await prisma.contentPublication.deleteMany();await prisma.contentAuditEvent.deleteMany();await prisma.schoolIdentity.deleteMany();await prisma.schoolProfile.deleteMany();await prisma.mediaAsset.deleteMany();await prisma.auditLog.deleteMany();await prisma.schoolSettings.deleteMany();await prisma.school.deleteMany();}
describe.sequential("School identity and profile PostgreSQL integration",()=>{
 beforeAll(async()=>{if(new URL(process.env.DATABASE_URL??"").pathname!=="/arrahmah_sms_test")throw new Error("Test DB required");await clean();actorId=crypto.randomUUID();const schools=await Promise.all([prisma.school.create({data:{schoolCode:"CONTENT_A",schoolName:"School A",identity:{create:{schoolName:"School A"}},profile:{create:{}}}}),prisma.school.create({data:{schoolCode:"CONTENT_B",schoolName:"School B",identity:{create:{schoolName:"School B"}},profile:{create:{}}}})]);schoolId=schools[0].id;otherSchoolId=schools[1].id;});
 afterAll(async()=>{await clean();await prisma.$disconnect();});
 it("updates a singleton transactionally with optimistic concurrency and audit",async()=>{const repo=new PrismaSchoolContentRepository();const current=await prisma.schoolIdentity.findUniqueOrThrow({where:{schoolId}});const updated=await repo.updateIdentity(schoolId,actorId,"identity-update",{schoolName:"Updated School",shortName:"Updated",tagline:"Tagline",expectedUpdatedAt:current.updatedAt.toISOString()}) as {schoolName:string;id:string};expect(updated.schoolName).toBe("Updated School");expect(await prisma.contentAuditEvent.count({where:{entityId:updated.id,action:"UPDATE"}})).toBe(1);await expect(repo.updateIdentity(schoolId,actorId,"stale",{schoolName:"Stale",expectedUpdatedAt:current.updatedAt.toISOString()})).rejects.toMatchObject({code:"STALE_UPDATE"});});
 it("rejects cross-school media and preserves the working copy",async()=>{const foreign=await prisma.mediaAsset.create({data:{schoolId:otherSchoolId,storageProvider:"TEST",storageKey:"foreign/logo.png",originalFilename:"logo.png",mimeType:"image/png",sizeBytes:3,checksum:"f".repeat(64),status:"ACTIVE",createdBy:actorId}});const repo=new PrismaSchoolContentRepository();const current=await prisma.schoolIdentity.findUniqueOrThrow({where:{schoolId}});await expect(repo.updateIdentity(schoolId,actorId,"foreign",{schoolName:current.schoolName,logoMediaId:foreign.id,expectedUpdatedAt:current.updatedAt.toISOString()})).rejects.toMatchObject({code:"INVALID_MEDIA_REFERENCE"});});
 it("publishes immutable identity and profile snapshots, then unpublishes",async()=>{const content=new PrismaSchoolContentRepository();let profile=await prisma.schoolProfile.findUniqueOrThrow({where:{schoolId}});await content.updateProfile(schoolId,actorId,"profile-update",{vision:"Vision",mission:"Mission",summary:"Summary",expectedUpdatedAt:profile.updatedAt.toISOString()});const publishing=new PrismaPublishingRepository();let identity=await prisma.schoolIdentity.findUniqueOrThrow({where:{schoolId}});const first=await publishing.publish({schoolId,entityType:"SCHOOL_IDENTITY",entityId:identity.id,expectedUpdatedAt:identity.updatedAt,actorUserId:actorId,requestId:"publish-1"});identity=await prisma.schoolIdentity.update({where:{schoolId},data:{tagline:"Changed"}});const second=await publishing.publish({schoolId,entityType:"SCHOOL_IDENTITY",entityId:identity.id,expectedUpdatedAt:identity.updatedAt,actorUserId:actorId,requestId:"publish-2"});expect([first.version,second.version]).toEqual([1,2]);expect(await prisma.contentPublication.count({where:{entityId:identity.id}})).toBe(2);expect(await publishing.listPublished(otherSchoolId,"SCHOOL_IDENTITY")).toHaveLength(0);profile=await prisma.schoolProfile.findUniqueOrThrow({where:{schoolId}});await publishing.publish({schoolId,entityType:"SCHOOL_PROFILE",entityId:profile.id,expectedUpdatedAt:profile.updatedAt,actorUserId:actorId,requestId:"profile-publish"});profile=await prisma.schoolProfile.findUniqueOrThrow({where:{schoolId}});await publishing.unpublish({schoolId,entityType:"SCHOOL_PROFILE",entityId:profile.id,expectedUpdatedAt:profile.updatedAt,actorUserId:actorId,requestId:"profile-unpublish"});expect(await publishing.listPublished(schoolId,"SCHOOL_PROFILE")).toHaveLength(0);expect((await prisma.schoolProfile.findUniqueOrThrow({where:{schoolId}})).status).toBe("DRAFT");});
});
