import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{prisma}from"@/lib/prisma";
import{PrismaGalleryAlbumRepository,PrismaGalleryItemRepository,PrismaProgramRepository,PrismaTeacherRepository,PrismaTestimonialRepository}from"@/modules/structured-content/infrastructure/prisma-repositories";

let a:string,b:string,mediaA:string,mediaB:string;const actor=crypto.randomUUID();
async function clean(){await prisma.contentPublicationHead.deleteMany();await prisma.contentPublication.deleteMany();await prisma.contentAuditEvent.deleteMany();await prisma.schoolIdentity.deleteMany();await prisma.schoolProfile.deleteMany();await prisma.galleryItem.deleteMany();await prisma.program.deleteMany();await prisma.teacherProfile.deleteMany();await prisma.galleryAlbum.deleteMany();await prisma.testimonial.deleteMany();await prisma.mediaAsset.deleteMany();await prisma.contactChannel.deleteMany();await prisma.socialLink.deleteMany();await prisma.callToAction.deleteMany();await prisma.auditLog.deleteMany();await prisma.schoolSettings.deleteMany();await prisma.school.deleteMany();}
describe.sequential("structured content repositories",()=>{
 beforeAll(async()=>{if(new URL(process.env.DATABASE_URL??"").pathname!=="/arrahmah_sms_test")throw new Error("Test database required.");await clean();[a,b]=(await Promise.all([prisma.school.create({data:{schoolCode:"SC_A",schoolName:"A"}}),prisma.school.create({data:{schoolCode:"SC_B",schoolName:"B"}})])).map(x=>x.id);[mediaA,mediaB]=(await Promise.all([prisma.mediaAsset.create({data:{schoolId:a,storageProvider:"TEST",storageKey:"a/x.jpg",originalFilename:"x.jpg",mimeType:"image/jpeg",sizeBytes:3,checksum:"a".repeat(64),status:"ACTIVE",createdBy:actor}}),prisma.mediaAsset.create({data:{schoolId:b,storageProvider:"TEST",storageKey:"b/x.jpg",originalFilename:"x.jpg",mimeType:"image/jpeg",sizeBytes:3,checksum:"b".repeat(64),status:"ACTIVE",createdBy:actor}})])).map(x=>x.id);});afterAll(async()=>{await clean();await prisma.$disconnect();});
 it("scopes Program uniqueness, update, and reorder",async()=>{const r=new PrismaProgramRepository();const x=await r.create(a,{code:"ONE",title:"One",slug:"one",summary:"S",description:"D",featuredMediaId:mediaA,sortOrder:0,isActive:true});await expect(r.create(a,{code:"ONE",title:"Dup",slug:"dup",summary:"S",description:"D",sortOrder:1,isActive:true})).rejects.toMatchObject({code:"DUPLICATE_CODE"});await expect(r.create(b,{code:"ONE",title:"One",slug:"one",summary:"S",description:"D",featuredMediaId:mediaB,sortOrder:0,isActive:true})).resolves.toBeTruthy();expect(await r.findById(b,x.id)).toBeNull();const y=await r.create(a,{code:"TWO",title:"Two",slug:"two",summary:"S",description:"D",sortOrder:1,isActive:true});const updated=await r.update(a,x.id,x.updatedAt,{title:"Updated"});await expect(r.update(a,x.id,x.updatedAt,{title:"Stale"})).rejects.toMatchObject({code:"STALE_UPDATE"});const items=await r.list(a);const token=items.reduce((m,v)=>m>v.updatedAt?m:v.updatedAt,new Date(0));expect((await r.reorder(a,[y.id,updated.id],token)).map(v=>v.id)).toEqual([y.id,x.id]);});
 it("persists Teacher, Gallery Album/Item, and Testimonial with scoped relations",async()=>{const teacher=await new PrismaTeacherRepository().create(a,{name:"Teacher",photoMediaId:mediaA,sortOrder:0,isActive:true});expect(teacher.schoolId).toBe(a);const albums=new PrismaGalleryAlbumRepository();const album=await albums.create(a,{title:"Album",slug:"album",coverMediaId:mediaA,sortOrder:0,isActive:true});const items=new PrismaGalleryItemRepository();await items.create(a,album.id,{mediaId:mediaA,caption:"Moment",sortOrder:0,isActive:true});await expect(items.create(a,album.id,{mediaId:mediaA,caption:null,sortOrder:1,isActive:true})).rejects.toMatchObject({code:"DUPLICATE_CODE"});const testimonial=await new PrismaTestimonialRepository().create(a,{authorName:"Parent",quote:"Good",avatarMediaId:mediaA,sortOrder:0,isActive:true});expect(testimonial.schoolId).toBe(a);});
});
