import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CalendarDays, CheckCircle2, Sparkles } from "lucide-react";
import { learningMomentsByProgram, programs, type Program } from "../data/programs";
import LearningMoments from "./LearningMoments";

function ListCards({ items, tone }: { items: string[]; tone: "teal" | "amber" }) {
  return <div className="grid gap-4 md:grid-cols-3">{items.map((item) => <article key={item} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-[0_10px_30px_rgba(15,23,42,0.05)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_40px_rgba(15,118,110,0.10)]"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${tone === "teal" ? "bg-teal-50 text-teal-700" : "bg-amber-50 text-amber-600"}`}><CheckCircle2 size={20} aria-hidden="true" /></span><p className="mt-4 font-semibold leading-7 text-slate-700">{item}</p></article>)}</div>;
}

export default function FeaturedProgramDetail({ program }: { program: Program }) {
  const learningMoments = learningMomentsByProgram[program.slug];
  const otherPrograms = programs.filter((item) => item.slug !== program.slug).slice(0, 3);
  return <main className="bg-[#F8FAFC]">
    <section className="relative overflow-hidden bg-[radial-gradient(circle_at_top_left,#ECFDF5,transparent_40%),radial-gradient(circle_at_top_right,#DBEAFE,transparent_35%),#FFFFFF] px-5 py-12 sm:px-6 lg:py-20"><div className="mx-auto max-w-[1240px]"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm text-slate-500"><Link href="/" className="hover:text-teal-700">Beranda</Link><span aria-hidden="true">/</span><Link href="/program" className="hover:text-teal-700">Program</Link><span aria-hidden="true">/</span><span className="font-semibold text-slate-700">{program.title}</span></nav><div className="mt-8 grid items-center gap-10 lg:grid-cols-[0.88fr_1.12fr] lg:gap-16"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-teal-700">Program Unggulan</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl lg:text-6xl">{program.title}</h1><p className="mt-5 text-base leading-8 text-slate-600 sm:text-lg">{program.description}</p><Link href="/program" className="mt-7 inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700 hover:border-teal-300 hover:text-teal-700"><ArrowLeft size={17} aria-hidden="true" />Kembali ke Program</Link></div><div className="relative h-[300px] overflow-hidden rounded-[32px_20px_32px_20px] border-[6px] border-white shadow-[0_28px_70px_rgba(15,118,110,0.16)] sm:h-[420px]"><Image src={program.image} alt={`Kegiatan ${program.title} di TK Islam Ar Rahmah 48`} fill preload sizes="(min-width: 1024px) 55vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/20 via-transparent to-white/5" /></div></div></div></section>

    <section className="bg-white px-5 py-20 sm:px-6 lg:py-28"><div className="mx-auto grid max-w-[1120px] gap-10 lg:grid-cols-2 lg:gap-20"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">Tentang Program</p><h2 className="mt-3 text-3xl font-extrabold text-slate-900 sm:text-4xl">Pengalaman Belajar yang Bermakna</h2><p className="mt-5 leading-8 text-slate-600">{program.about}</p></div><div className="rounded-[26px] border border-teal-100 bg-teal-50/60 p-6 sm:p-8"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-teal-700 shadow-sm"><CalendarDays size={23} aria-hidden="true" /></span><h3 className="mt-5 text-xl font-bold text-slate-900">Jadwal dan Frekuensi</h3><p className="mt-3 leading-7 text-slate-600">{program.frequency}</p></div></div></section>

    <section className="px-5 py-20 sm:px-6 lg:py-28"><div className="mx-auto max-w-[1120px]"><div className="mb-10 text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">Tujuan Pembelajaran</p><h2 className="mt-3 text-3xl font-extrabold text-slate-900 sm:text-4xl">Arah Pembelajaran {program.title}</h2></div><ListCards items={program.objectives} tone="teal" /></div></section>

    <section className="bg-white px-5 py-20 sm:px-6 lg:py-28"><div className="mx-auto grid max-w-[1120px] gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">Kegiatan Anak</p><h2 className="mt-3 text-3xl font-extrabold text-slate-900">Belajar Aktif dan Menyenangkan</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{program.activities.map((activity) => <div key={activity} className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><Sparkles size={18} className="shrink-0 text-amber-500" aria-hidden="true" /><span className="text-sm font-semibold text-slate-700">{activity}</span></div>)}</div></div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-600">Manfaat untuk Anak</p><h2 className="mt-3 text-3xl font-extrabold text-slate-900">Bekal Positif untuk Bertumbuh</h2><div className="mt-7"><ListCards items={program.benefits} tone="amber" /></div></div></div></section>

    <LearningMoments description={learningMoments.description} moments={learningMoments.moments} />

    <section className="bg-white px-5 py-20 sm:px-6 lg:py-24"><div className="mx-auto max-w-[1120px]"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-700">Jelajahi</p><h2 className="mt-3 text-3xl font-extrabold text-slate-900">Program Lainnya</h2></div><Link href="/program" className="inline-flex w-fit items-center gap-2 rounded-xl border border-teal-700 px-4 py-2 text-sm font-bold text-teal-700 hover:bg-teal-50"><ArrowLeft size={16} aria-hidden="true" />Kembali ke Semua Program</Link></div><div className="mt-9 grid gap-5 md:grid-cols-3">{otherPrograms.map((item) => <Link key={item.slug} href={`/program/${item.slug}`} className="group overflow-hidden rounded-[24px] border border-slate-200 bg-white shadow-[0_10px_30px_rgba(15,23,42,0.05)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_40px_rgba(15,118,110,0.10)]"><div className="relative aspect-[16/10] overflow-hidden"><Image src={item.image} alt={`Kegiatan program ${item.title}`} fill sizes="(min-width:768px) 33vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105 motion-reduce:transition-none" /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/25 to-transparent" /></div><div className="p-5"><h3 className="text-lg font-bold text-slate-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{item.description}</p><span className="mt-4 inline-flex text-sm font-bold text-teal-700">Pelajari Program →</span></div></Link>)}</div></div></section>
  </main>;
}
