import{apiError,ok,requestId}from"@/lib/api";
import{getCurrentActor}from"@/lib/auth/session";
import{unauthenticated}from"@/modules/cms/domain/errors";
import{galleryItemService,galleryAlbumService,programService,teacherService,testimonialService}from"@/modules/structured-content/application/services";
import{galleryAlbumCreateSchema,galleryAlbumUpdateSchema,galleryItemCreateSchema,galleryItemUpdateSchema,programCreateSchema,programUpdateSchema,reorderSchema,teacherCreateSchema,teacherUpdateSchema,testimonialCreateSchema,testimonialUpdateSchema}from"@/modules/structured-content/validation/schemas";
import{cmsCreate,cmsList,cmsOrder,cmsRead,cmsUpdate,lifecycle}from"@/modules/publishing/presentation/route-handlers";
import type{PublishableType}from"@/modules/publishing/domain/contracts";

const domains={programs:{service:programService,create:programCreateSchema,update:programUpdateSchema,type:"PROGRAM"},teachers:{service:teacherService,create:teacherCreateSchema,update:teacherUpdateSchema,type:"TEACHER_PROFILE"},galleries:{service:galleryAlbumService,create:galleryAlbumCreateSchema,update:galleryAlbumUpdateSchema,type:"GALLERY_ALBUM"},testimonials:{service:testimonialService,create:testimonialCreateSchema,update:testimonialUpdateSchema,type:"TESTIMONIAL"}}as const;
function domain(name:string){return domains[name as keyof typeof domains];}
async function params(ctx:RouteContext<"/api/v1/cms/[collection]/[[...path]]">){const p=await ctx.params;return{d:domain(p.collection),path:p.path??[]};}
export async function GET(req:Request,ctx:RouteContext<"/api/v1/cms/[collection]/[[...path]]">){const{d,path}=await params(ctx);if(!d)return new Response(null,{status:404});if(!path.length)return cmsList(req,d.service);if(path.length===1)return cmsRead(req,path[0],d.service);if(path.length===2&&path[1]==="publication-status")return lifecycle(req,path[0],d.type as PublishableType,"status");return new Response(null,{status:404});}
export async function POST(req:Request,ctx:RouteContext<"/api/v1/cms/[collection]/[[...path]]">){const{d,path}=await params(ctx);if(!d)return new Response(null,{status:404});if(!path.length)return cmsCreate(req,d.service,d.create);if(path.length===2&&(path[1]==="publish"||path[1]==="unpublish"))return lifecycle(req,path[0],d.type as PublishableType,path[1]);if(d.type==="GALLERY_ALBUM"&&path.length===2&&path[1]==="items")return galleryMutation(req,path[0],"add");return new Response(null,{status:404});}
export async function PATCH(req:Request,ctx:RouteContext<"/api/v1/cms/[collection]/[[...path]]">){const{d,path}=await params(ctx);if(!d)return new Response(null,{status:404});if(path.length===1)return cmsUpdate(req,path[0],d.service,d.update);if(d.type==="GALLERY_ALBUM"&&path.length===3&&path[1]==="items")return galleryMutation(req,path[0],"update",path[2]);return new Response(null,{status:404});}
export async function PUT(req:Request,ctx:RouteContext<"/api/v1/cms/[collection]/[[...path]]">){const{d,path}=await params(ctx);if(!d)return new Response(null,{status:404});if(path.length===1&&path[0]==="order")return cmsOrder(req,d.service);if(d.type==="GALLERY_ALBUM"&&path.length===3&&path[1]==="items"&&path[2]==="order")return galleryMutation(req,path[0],"order");return new Response(null,{status:404});}
async function galleryMutation(req:Request,albumId:string,action:"add"|"update"|"order",itemId?:string){const r=requestId(req);try{const actor=await getCurrentActor();if(!actor)throw unauthenticated();const body=await req.json();if(action==="add")return ok(await galleryItemService.add(actor,r,albumId,galleryItemCreateSchema.parse(body)),r,201);if(action==="update")return ok(await galleryItemService.update(actor,r,itemId!,galleryItemUpdateSchema.parse(body)),r);const input=reorderSchema.parse(body);return ok(await galleryItemService.reorder(actor,r,albumId,input.ids,input.expectedCollectionUpdatedAt),r)}catch(e){return apiError(e,r)}}
