"use client";
import { useState, type FormEvent } from "react";

type Field = { name: string; label: string; multiline?: boolean; required?: boolean; maxLength?: number };
export default function SchoolContentEditor({ endpoint, initial, fields, readOnly }: { endpoint: string; initial: Record<string, unknown>; fields: Field[]; readOnly: boolean }) {
  const [data, setData] = useState(initial); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function request(path: string, method: "PUT" | "POST") { setBusy(true); setMessage(""); try { const payload = method === "PUT" ? { ...Object.fromEntries(fields.map(({ name }) => [name, data[name] === "" ? null : data[name]])), expectedUpdatedAt: data.updatedAt } : { expectedUpdatedAt: data.updatedAt }; const response = await fetch(`${endpoint}${path}`, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Permintaan gagal."); if (method === "PUT") setData(result.data); else { const current = await fetch(endpoint).then((value) => value.json()); if (current.data) setData(current.data); } setMessage(path === "/publish" ? "Konten berhasil dipublikasikan." : path === "/unpublish" ? "Publikasi berhasil dihentikan." : "Perubahan berhasil disimpan."); } catch (error) { setMessage(error instanceof Error ? error.message : "Permintaan gagal."); } finally { setBusy(false); } }
  const submit = (event: FormEvent) => { event.preventDefault(); void request("", "PUT"); };
  return <form onSubmit={submit} className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
    <div className="grid gap-5 md:grid-cols-2">{fields.map((field) => <label key={field.name} className={field.multiline ? "md:col-span-2" : ""}><span className="mb-2 block text-sm font-semibold text-slate-700">{field.label}</span>{field.multiline ? <textarea rows={5} required={field.required} maxLength={field.maxLength} disabled={readOnly || busy} value={String(data[field.name] ?? "")} onChange={(event) => setData((current) => ({ ...current, [field.name]: event.target.value }))} className="w-full rounded-2xl border border-slate-300 px-4 py-3 focus:border-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-100 disabled:bg-slate-50" /> : <input required={field.required} maxLength={field.maxLength} disabled={readOnly || busy} value={String(data[field.name] ?? "")} onChange={(event) => setData((current) => ({ ...current, [field.name]: event.target.value }))} className="h-12 w-full rounded-2xl border border-slate-300 px-4 focus:border-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-100 disabled:bg-slate-50" />}</label>)}</div>
    {message && <p role="status" className="rounded-xl bg-teal-50 px-4 py-3 text-sm font-medium text-teal-900">{message}</p>}
    {!readOnly && <div className="flex flex-wrap gap-3"><button disabled={busy} className="h-11 rounded-xl bg-teal-700 px-5 font-semibold text-white hover:bg-teal-800 disabled:opacity-50">Simpan Draft</button><button type="button" disabled={busy} onClick={() => void request("/publish", "POST")} className="h-11 rounded-xl border border-teal-700 px-5 font-semibold text-teal-800 hover:bg-teal-50 disabled:opacity-50">Publish</button><button type="button" disabled={busy} onClick={() => void request("/unpublish", "POST")} className="h-11 rounded-xl border border-slate-300 px-5 font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50">Unpublish</button></div>}
  </form>;
}
